"""
for_gpt_builder.py

Builds a single `for_gpt.py` file that contains (most) project source files inline.
Intended for sharing the codebase in one paste/file.

Usage:
  python for_gpt_builder.py

By default, this script:
- skips virtualenvs, git folders, caches
- skips common "junk" files (.env, .gitignore, etc.)
- skips binary / large files and dataset/model artifacts (csv/pkl)
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import os
from pathlib import Path
from typing import Iterable


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_OUT = PROJECT_ROOT / "for_gpt.py"


SKIP_DIR_NAMES = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".idea",
    ".vscode",
    "node_modules",
    "dist",
    "build",
    "assets",
}

SKIP_FILE_NAMES = {
    ".env",
    ".gitignore",
    "for_gpt.py",
    "for_gpt_builder.py",
}

SKIP_EXTENSIONS = {
    # data / artifacts
    ".csv",
    ".pkl",
    ".parquet",
    ".feather",
    ".zip",
    ".gz",
    ".7z",
    # media / binaries
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".pdf",
    ".mp3",
    ".mp4",
    ".wav",
    ".exe",
    ".dll",
    ".so",
}

DEFAULT_MAX_BYTES = 200_000  # per file


@dataclass(frozen=True)
class CollectedFile:
    relpath: str
    text: str
    size: int


def _is_under_skipped_dir(path: Path) -> bool:
    return any(part in SKIP_DIR_NAMES for part in path.parts)


def _should_include(path: Path, max_bytes: int) -> bool:
    if not path.is_file():
        return False
    if _is_under_skipped_dir(path.relative_to(PROJECT_ROOT)):
        return False

    if path.name in SKIP_FILE_NAMES:
        return False

    if path.suffix.lower() in SKIP_EXTENSIONS:
        return False

    try:
        size = path.stat().st_size
    except Exception:
        return False
    if size > int(max_bytes):
        return False

    return True


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")


def collect_files(root: Path, max_bytes: int) -> list[CollectedFile]:
    out: list[CollectedFile] = []

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIR_NAMES]
        for name in filenames:
            p = Path(dirpath) / name
            if not _should_include(p, max_bytes=max_bytes):
                continue
            rel = p.relative_to(root).as_posix()
            text = _read_text(p)
            size = p.stat().st_size
            out.append(CollectedFile(relpath=rel, text=text, size=int(size)))
    out.sort(key=lambda x: x.relpath)
    return out


def _render(files: Iterable[CollectedFile]) -> str:
    files = list(files)
    now = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")

    header_lines = [
        "# AUTOGENERATED FILE - DO NOT EDIT",
        f"# Built by: for_gpt_builder.py",
        f"# Built at (UTC): {now}",
        "#",
        "# Contents: project files inlined with separators.",
        "",
        "FILES = [",
    ]
    for f in files:
        header_lines.append(f"    {f.relpath!r},")
    header_lines += [
        "]",
        "",
    ]

    parts: list[str] = ["\n".join(header_lines)]
    for f in files:
        parts.append("=" * 88)
        parts.append(f"# FILE: {f.relpath} ({f.size} bytes)")
        parts.append("=" * 88)
        parts.append(f.text.rstrip("\n"))
        parts.append("")  # trailing newline after each file

    return "\n".join(parts) + "\n"


def build(out_path: Path, max_bytes: int) -> None:
    files = collect_files(PROJECT_ROOT, max_bytes=max_bytes)
    payload = _render(files)
    out_path.write_text(payload, encoding="utf-8")
    print(f"Built: {out_path}")
    print(f"Files included: {len(files)}")


def main() -> None:
    build(out_path=DEFAULT_OUT, max_bytes=DEFAULT_MAX_BYTES)


if __name__ == "__main__":
    main()